config/routes.rb
Rails.application.routes.draw do
  root 'customers#index'
  resources :customers do
    resources :procedures

    resources :services
    resources :reclamations
    resources :appointments
    resources :historials

  end

  get '/ars', to: 'customers#ars'
  get '/cenasa', to: 'customers#cenasa'
  get '/naseguro', to: 'customers#naseguro'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :customer
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  include ActionController::MimeResponds

  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
    @customer = Customer.find(params[:id])
    @service = @customer.services.find(params[:id])
  end




  # POST /services
  # POST /services.json
  def create
    @customer = Customer.find(params[:customer_id])
    @service = @customer.service.new(service_params)

    respond_to do |format|
      if @service.save
        
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    @service = Service.find(params[:id])
    respond_to do |format|
      if @service.update_attributes(service_params)
        format.html { redirect_to @customer, success: 'Service was successfully updated.' }
        format.json { respond_with_bip(@service) }
      else
        format.html { render action: 'edit'}
        format.json { respond_with_bip(@service) }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
   @service = Service.find(params[:id])
   @service.destroy
   respond_to do |format|
     format.js { render :file => "/customers/serv.js.erb"}
   end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:customer_id, :process, :code, :reclaimed, :authorized, :difference)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_with(model: service, local: true) do |form| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.text_field :customer_id %>
  </div>

  <div class="field">
    <%= form.label :process %>
    <%= form.text_field :process %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.number_field :code %>
  </div>

  <div class="field">
    <%= form.label :reclaimed %>
    <%= form.number_field :reclaimed %>
  </div>

  <div class="field">
    <%= form.label :authorized %>
    <%= form.number_field :authorized %>
  </div>

  <div class="field">
    <%= form.label :difference %>
    <%= form.number_field :difference %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/services/_service.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>



<td><%= best_in_place customer_service_path(), :process %></td>

<%= link_to customer_service_path(service.customer, service), method: :delete, data: { confirm: 'Are you sure?' } do %>
<button type="button" name="button">DELETE</button>
<% end %>

<br>

app/views/services/destroy.js.erb
$('.delete').on('ajax:success', function() {
  $(this).closest('.container_row').fadeOut();
});

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Services</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Process</th>
      <th>Code</th>
      <th>Reclaimed</th>
      <th>Authorized</th>
      <th>Difference</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.customer %></td>
        <td><%= service.process %></td>
        <td><%= service.code %></td>
        <td><%= service.reclaimed %></td>
        <td><%= service.authorized %></td>
        <td><%= service.difference %></td>
        <td><%= link_to 'Show', service %></td>
        <td><%= link_to 'Edit', edit_service_path(service) %></td>
        <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_service_path %>

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @service.customer %>
</p>

<p>
  <strong>Process:</strong>
  <%= @service.process %>
</p>

<p>
  <strong>Code:</strong>
  <%= @service.code %>
</p>

<p>
  <strong>Reclaimed:</strong>
  <%= @service.reclaimed %>
</p>

<p>
  <strong>Authorized:</strong>
  <%= @service.authorized %>
</p>

<p>
  <strong>Difference:</strong>
  <%= @service.difference %>
</p>



<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>