config/routes.rb
Rails.application.routes.draw do
  root 'customers#index'
  resources :customers do
    resources :procedures

    resources :services
    resources :reclamations
    resources :appointments
    resources :historials

  end

  get '/ars', to: 'customers#ars'
  get '/cenasa', to: 'customers#cenasa'
  get '/naseguro', to: 'customers#naseguro'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reclamation.rb
class Reclamation < ApplicationRecord
  belongs_to :customer

  enum therapist: [:Dr_Enrique_Antonio_paredes, :Lic_Josefina_García, :Lic_Alejandro_Colón]



end

app/controllers/reclamations_controller.rb
class ReclamationsController < ApplicationController
  include ActionController::MimeResponds
  before_action :set_reclamation, only: [:show, :edit, :update, :destroy]

  # GET /reclamations
  # GET /reclamations.json
  def index
    @reclamations = Reclamation.all
  end

  # GET /reclamations/1
  # GET /reclamations/1.json
  def show
  end

  # GET /reclamations/new
  def new
    @reclamation = Reclamation.new
  end

  # GET /reclamations/1/edit
  def edit
    @customer = Customer.find(params[:id])
    @reclamation = @customer.reclamations.find(params[:id])
  end

  # POST /reclamations
  # POST /reclamations.json
  def create
    @customer = Customer.find(params[:customer_id])
    @reclamation = @customer.reclamation.new(reclamation_params)

    respond_to do |format|
      if @reclamation.save

      else
        format.html { render :new }
        format.json { render json: @reclamation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reclamations/1
  # PATCH/PUT /reclamations/1.json
  def update
    @reclamation = Reclamation.find(params[:id])

    respond_to do |format|
      if @reclamation.update(reclamation_params)
        format.html { redirect_to @reclamation, success: 'Guardado Correctamente' }
        format.json { render :show, status: :ok, location: @reclamation }
      else
        format.html { render :edit }
        format.json { render json: @reclamation.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    @reclamation = Reclamation.find(params[:id])
    respond_to do |format|
      if @reclamation.update(reclamation_params)
        format.html { redirect_to @reclamation, success: 'Guardado Correctamente' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit'}
        format.json { render json: @reclamation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reclamations/1
  # DELETE /reclamations/1.json
  def destroy
   @reclamation = Reclamation.find(params[:id])
   customer = @reclamation.customer
   @reclamation.destroy
   respond_to do |format|
       format.js {render inline: "location.reload();" }
   end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reclamation
      @reclamation = Reclamation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reclamation_params
      params.require(:reclamation).permit(:customer_id, :authNum, :therapiesNum, :doctor, :creationDate, :ensureReclam, :diagnostic, :therapist)
    end
end

app/helpers/reclamations_helper.rb
module ReclamationsHelper
end

app/views/reclamations/_form.html.erb
<%= form_with(model: reclamation, local: true) do |form| %>
  <% if reclamation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reclamation.errors.count, "error") %> prohibited this reclamation from being saved:</h2>

      <ul>
      <% reclamation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.text_field :customer_id %>
  </div>

  <div class="field">
    <%= form.label :authNum %>
    <%= form.number_field :authNum %>
  </div>

  <div class="field">
    <%= form.label :therapiesNum %>
    <%= form.number_field :therapiesNum %>
  </div>

  <div class="field">
    <%= form.label :doctor %>
    <%= form.number_field :doctor %>
  </div>

  <div class="field">
    <%= form.label :creationDate %>
    <%= form.number_field :creationDate %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reclamations/_reclamation.html.erb
        <%= reclamation.therapiesNum %>
        <%= link_to customer_reclamation_path(reclamation.customer, reclamation), method: :delete, data: { confirm: 'Are you sure?' } do %>
        <%=image_tag("edit_delete.png")%>

        <% end %>
        <br>

app/views/reclamations/edit.html.erb
<h1>Editing Reclamation</h1>

<%= render 'form', reclamation: @reclamation %>

<%= link_to 'Show', @reclamation %> |
<%= link_to 'Back', reclamations_path %>

app/views/reclamations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reclamations</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Authnum</th>
      <th>Therapiesnum</th>
      <th>Doctor</th>
      <th>Creationdate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reclamations.each do |reclamation| %>
      <tr>
        <td><%= reclamation.customer %></td>
        <td><%= reclamation.authNum %></td>
        <td><%= reclamation.therapiesNum %></td>
        <td><%= reclamation.doctor %></td>
        <td><%= reclamation.creationDate %></td>
        <td><%= link_to 'Show', reclamation %></td>
        <td><%= link_to 'Edit', edit_reclamation_path(reclamation) %></td>
        <td><%= link_to 'Destroy', reclamation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reclamation', new_reclamation_path %>

app/views/reclamations/new.html.erb
<h1>New Reclamation</h1>

<%= render 'form', reclamation: @reclamation %>

<%= link_to 'Back', reclamations_path %>

app/views/reclamations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @reclamation.customer %>
</p>

<p>
  <strong>Authnum:</strong>
  <%= @reclamation.authNum %>
</p>

<p>
  <strong>Therapiesnum:</strong>
  <%= @reclamation.therapiesNum %>
</p>

<p>
  <strong>Doctor:</strong>
  <%= @reclamation.doctor %>
</p>

<p>
  <strong>Creationdate:</strong>
  <%= @reclamation.creationDate %>
</p>

<%= link_to 'Edit', edit_reclamation_path(@reclamation) %> |
<%= link_to 'Back', reclamations_path %>