config/routes.rb
Rails.application.routes.draw do
  root 'customers#index'
  resources :customers do
    resources :procedures

    resources :services
    resources :reclamations
    resources :appointments
    resources :historials

  end

  get '/ars', to: 'customers#ars'
  get '/cenasa', to: 'customers#cenasa'
  get '/naseguro', to: 'customers#naseguro'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/historial.rb
class Historial < ApplicationRecord
  belongs_to :customer
end

app/controllers/historials_controller.rb
class HistorialsController < ApplicationController
  before_action :set_historial, only: [:show, :edit, :update, :destroy]

  # GET /historials
  # GET /historials.json
  def index
    @historials = Historial.all
  end

  # GET /historials/1
  # GET /historials/1.json
  def show
  end

  # GET /historials/new
  def new
    @historial = Historial.new
  end

  # GET /historials/1/edit
  def edit
  end

  # POST /historials
  # POST /historials.json
  def create
    @customer = Customer.find(params[:customer_id])
    @historial = @customer.historial.new(historial_params)

    respond_to do |format|
      if @historial.save
        format.html { redirect_to @customer}
        format.json { render :show, status: :created, location: @historial }
      else
        format.html { render :new }
        format.json { render json: @historial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /historials/1
  # PATCH/PUT /historials/1.json
  def update
    respond_to do |format|
      if @historial.update(historial_params)
        format.html { redirect_to @historial, notice: 'Historial was successfully updated.' }
        format.json { render :show, status: :ok, location: @historial }
      else
        format.html { render :edit }
        format.json { render json: @historial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /historials/1
  # DELETE /historials/1.json
  def destroy
    @historial = Historial.find(params[:id])
    @customer = Customer.find(params[:customer_id])

    @historial.destroy
    respond_to do |format|
        format.js {render inline: "location.reload();" }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_historial
      @historial = Historial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def historial_params
      params.require(:historial).permit(:padecimiento, :status, :patologico, :familiares, :examen, :anexo, :unificada, :autorizar, :firma, :customer_id)
    end
end

app/helpers/historials_helper.rb
module HistorialsHelper
end

app/views/historials/_form.html.erb
<%= form_with(model: historial, local: true) do |form| %>
  <% if historial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(historial.errors.count, "error") %> prohibited this historial from being saved:</h2>

      <ul>
      <% historial.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :padecimiento %>
    <%= form.text_field :padecimiento %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :patologico %>
    <%= form.text_field :patologico %>
  </div>

  <div class="field">
    <%= form.label :familiares %>
    <%= form.text_field :familiares %>
  </div>

  <div class="field">
    <%= form.label :examen %>
    <%= form.text_field :examen %>
  </div>

  <div class="field">
    <%= form.label :anexo %>
    <%= form.text_field :anexo %>
  </div>

  <div class="field">
    <%= form.label :unificada %>
    <%= form.text_field :unificada %>
  </div>

  <div class="field">
    <%= form.label :autorizar %>
    <%= form.text_field :autorizar %>
  </div>

  <div class="field">
    <%= form.label :firma %>
    <%= form.text_field :firma %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/historials/edit.html.erb
<h1>Editing Historial</h1>

<%= render 'form', historial: @historial %>

<%= link_to 'Show', @historial %> |
<%= link_to 'Back', historials_path %>

app/views/historials/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Historials</h1>

<table>
  <thead>
    <tr>
      <th>Padecimiento</th>
      <th>Status</th>
      <th>Patologico</th>
      <th>Familiares</th>
      <th>Examen</th>
      <th>Anexo</th>
      <th>Unificada</th>
      <th>Autorizar</th>
      <th>Firma</th>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @historials.each do |historial| %>
      <tr>
        <td><%= historial.padecimiento %></td>
        <td><%= historial.status %></td>
        <td><%= historial.patologico %></td>
        <td><%= historial.familiares %></td>
        <td><%= historial.examen %></td>
        <td><%= historial.anexo %></td>
        <td><%= historial.unificada %></td>
        <td><%= historial.autorizar %></td>
        <td><%= historial.firma %></td>
        <td><%= historial.customer %></td>
        <td><%= link_to 'Show', historial %></td>
        <td><%= link_to 'Edit', edit_historial_path(historial) %></td>
        <td><%= link_to 'Destroy', historial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Historial', new_historial_path %>

app/views/historials/new.html.erb
<h1>New Historial</h1>

<%= render 'form', historial: @historial %>

<%= link_to 'Back', historials_path %>

app/views/historials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Padecimiento:</strong>
  <%= @historial.padecimiento %>
</p>

<p>
  <strong>Status:</strong>
  <%= @historial.status %>
</p>

<p>
  <strong>Patologico:</strong>
  <%= @historial.patologico %>
</p>

<p>
  <strong>Familiares:</strong>
  <%= @historial.familiares %>
</p>

<p>
  <strong>Examen:</strong>
  <%= @historial.examen %>
</p>

<p>
  <strong>Anexo:</strong>
  <%= @historial.anexo %>
</p>

<p>
  <strong>Unificada:</strong>
  <%= @historial.unificada %>
</p>

<p>
  <strong>Autorizar:</strong>
  <%= @historial.autorizar %>
</p>

<p>
  <strong>Firma:</strong>
  <%= @historial.firma %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @historial.customer %>
</p>

<%= link_to 'Edit', edit_historial_path(@historial) %> |
<%= link_to 'Back', historials_path %>