config/routes.rb
Rails.application.routes.draw do
  root 'customers#index'
  resources :customers do
    resources :procedures

    resources :services
    resources :reclamations
    resources :appointments
    resources :historials

  end

  get '/ars', to: 'customers#ars'
  get '/cenasa', to: 'customers#cenasa'
  get '/naseguro', to: 'customers#naseguro'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/procedure.rb
class Procedure < ApplicationRecord
  belongs_to :customer
end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
  before_action :set_procedure, only: [:show, :edit, :update, :destroy]

  # GET /procedures
  # GET /procedures.json
  def index
    @procedures = Procedure.all
  end

  # GET /procedures/1
  # GET /procedures/1.json
  def show
  end

  # GET /procedures/new
  def new
    @procedure = Procedure.new
  end

  # GET /procedures/1/edit
  def edit
  end

  # POST /procedures
  # POST /procedures.json
  def create
    @customer = Customer.find(params[:customer_id])
    @procedure = @customer.procedure.new(procedure_params)

    respond_to do |format|
      if @procedure.save
        format.html { redirect_to @customer}
        format.json { render :show, status: :created, location: @procedure }
      else
        format.html { render :new }
        format.json { render json: @procedure.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /procedures/1
  # PATCH/PUT /procedures/1.json
  def update
    respond_to do |format|
      if @procedure.update(procedure_params)
        format.html { redirect_to @procedure, notice: 'Procedure was successfully updated.' }
        format.json { render :show, status: :ok, location: @procedure }
      else
        format.html { render :edit }
        format.json { render json: @procedure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /procedures/1
  # DELETE /procedures/1.json
  def destroy
    @procedure = Procedure.find(params[:id])
    @customer = Customer.find(params[:customer_id])

    @procedure.destroy
    respond_to do |format|
      format.js {render inline: "location.reload();" }

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_procedure
      @procedure = Procedure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def procedure_params
      params.require(:procedure).permit(:customer_id, :conclusion, :description, :plan, :conclusion1, :conclusion2 )
    end
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/views/procedures/_form.html.erb
<%= form_with(model: procedure, local: true) do |form| %>
  <% if procedure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(procedure.errors.count, "error") %> prohibited this procedure from being saved:</h2>

      <ul>
      <% procedure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.text_field :customer_id %>
  </div>

  <div class="field">
    <%= form.label :conclusion %>
    <%= form.text_field :conclusion %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/procedures/edit.html.erb
<h1>Editing Procedure</h1>

<%= render 'form', procedure: @procedure %>

<%= link_to 'Show', @procedure %> |
<%= link_to 'Back', procedures_path %>

app/views/procedures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Procedures</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Conclusion</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @procedures.each do |procedure| %>
      <tr>
        <td><%= procedure.customer %></td>
        <td><%= procedure.conclusion %></td>
        <td><%= procedure.description %></td>
        <td><%= link_to 'Show', procedure %></td>
        <td><%= link_to 'Edit', edit_procedure_path(procedure) %></td>
        <td><%= link_to 'Destroy', procedure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Procedure', new_procedure_path %>

app/views/procedures/new.html.erb
<h1>New Procedure</h1>

<%= render 'form', procedure: @procedure %>

<%= link_to 'Back', procedures_path %>

app/views/procedures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @procedure.customer %>
</p>

<p>
  <strong>Conclusion:</strong>
  <%= @procedure.conclusion %>
</p>

<p>
  <strong>Description:</strong>
  <%= @procedure.description %>
</p>

<%= link_to 'Edit', edit_procedure_path(@procedure) %> |
<%= link_to 'Back', procedures_path %>